var messages = {
	"Null":["Me: "],
	"KitchenInitial" : ["Me: I should run to the store and buy a delicious turkey!"],
	"CannotBuyTurkey" : ["Me: I barely have time for ONE turkey, let alone TWO!"],
	"NoMoney" : ["Me: I can't afford this!"],
	"BuyTurkeyFirst" : ["Me: I should buy a turkey first!"],
	"EmptyOven" : ["Me: Ah, the oven is already preheated..."],
	"OpenDoor" :["Me: I should probably try opening the oven door to measure the turkey's temperature"]
}

//Terrible Results
var terrible = [
"Grandpa: Outrageous. I didn't fight for freedom for this kind of meal.",
"Grandpa: I could have cooked a better fowl with a flamethrower in Korea.",
"Grandma: My sister can make feast out of a potato. What is this?",
"Dad: Don't expect my blessing.",
"Mom: No thanks, I'm actually a vegetarian.",
"Brother: Who taught you how to cook?",
"Brother: What an awful turkey.",
"Girlfriend: I'm leaving you honey. It's not you, its the turkey.",
"Cat: Meow Meow ('Get out of my house!')"];

//Subpar Results
var subPar = [
"Grandpa: My fake teeth can't chew through this tough turkey.",
"Grandpa: Treat the turkey with respect next time.",
"Grandma: Dear grandchild, next year let Grandmother do cooking.",
"Dad: I had high expectations from you.",
"Dad: You've brought shame to your family.",
"Dad: Not bad, but it could have been better.",
"Mom: Remember, it is the thought that matters.",
"Mom: You are welcome here no matter how well you cook.",
"Mom: Honey, I think this turkey could have turned out better.",
"Brother: Uhh, What's for dessert?",
"Brother: We should get a pre-baked turkey next time",
"Girlfriend: Hey, the cat seems to like it.",
"Girlfriend: We'll have to go to some cooking classes together.",
"Cat: Hisssssss"];

//Average Results
var average = [
"Grandpa: Hmm. Passable.",
"Grandma: This turkey tastes good, you have done well.",
"Dad: Pretty decent turkey have you cooked here.",
"Mom: Tastes better than store cooked turkeys.",
"Brother: This is way better than I expected.",
"Girlfriend: Not bad.",
"Cat: Meow meow ('I may not leave a present in your shoes today')"];

//Great Results
var great = [
"Grandpa: Fine job, sonny! Just like the golden days.",
"Grandpa: Tender and juicy, just the way I like it.",
"Grandma: Such a talented little cook. Welcome to family.",
"Grandma: Most enjoyable dinner. Now, who wants baked apples?",
"Dad: Good and meaty, mmm-mmm!",
"Mom: The second best turkey I have ever had!",
"Mom: You should teach me your secrets",
"Brother: Way to go, this turkey is fantastic.",
"Girlfriend: Oh, what a nice turkey.",
"Cat: Meow MEOW! ('I am pleased, human')"];

//Perfect Results
var perfect = [
"Grandpa: Damn good gobsmackingly delicious piece of freedom!",
"Grandma: Excellent! You will cook festival dinner next year, yes?",
"Dad: Finger-licking perfection!",
"Mom: This turkey is delicious. Let's get you two wed immediately!",
"Mom: Never have I had a more scrumptious turkey!",
"Brother: All-praise the turkeymeister!",
"Girlfriend: Bite after bite of gourmet delight!",
"Girlfriend: We should get married. Tonight!",
"Cat: Puuuurrrrrrr"];


var story = {

"Duck Story":
["Dad: So I was in the office last week, typing up the TPS reports that need to be turned in every Friday, when I heard a quacking sound.",
"Dad: I thought it was Larry again. He has one of those old Blackintosh computers at his desk, you know, the ones with the smiley winking face.",
"Brother: Dad, that's such old technology. When is your company going to upgrade to SuckBox 87?",
"Dad: I know, but let me finish my story. Well, you know how when you click or an alert box comes up the computer can be set to a quacking sound?",
"Dad: So I tell Larry, what's up with all his alert boxes.",
"Mom: Who's Larry again hun?",
"Dad: He's my stall partner. We share he cubicle remember? So he turns around in his office chair, and asks 'what?'",
"Dad: 'The quacking, what's with all the quacking?'",
"Dad: 'I'm not doing it', he tells me.",
"Dad: 'Well, It isn't me.'",
"Dad: Just then the quacking noise happened again.",
"Dad: 'Did you hear that Larry?'",
"Dad: 'Yeah.'",
"Dad: We poked our head above the cubicle to look out and didn't see anybody else in the room. Yet the quacking came again.",
"Dad: Besides the quacking, the room had fallen very silent.",
"Mom: So, what did ya do?",
"Dad: I droop down on my hands and knees, and that's when it got me.",
"Mom: Mercy!",
"Brother: You got attacked by a duck?",
"Dad: That duck ran into me, face first. In its flight to escape, it pooped on my hands. Lucky me.",
"Dad: Larry and I grabbed a few guys on break and we corralled the duck out of the office.",
"Dad: Some of the guys wanted to keep it as a pet, but these are the same guys who don't get much done anyways. No help to office productivity.",
"Grandma: Son, You let a good meal go to waste.",
"Dad: Mom, we don't eat ducks we find on the street. That's just cruel.",
"Grandma: That doesn't stop those Chinese from eating street cats and dogs. Why do you think there are all those missing pet posters in the neighborhood?",
"Mom: Oh good lord!",
"Dad: Mom, you should stop spreading those rumors. It is cars and wild animals.",
"Grandma: Oh I'm sure those are SOME of the reasons. But lying to yourself isn't good honey.",
"Cat: Meow.",
"Dad: Oh hey Kasey. You like being an indoor cat don't you? Don't have to worry about all those cars and wild animals. Don't you little girl?",
"Grandma: And Chinese.",
"Dad: Mooom!"],

"Golf Story":
["Grandpa: Son, what's your par on the John Milton Golf Course?.",
"Dad: I'm a little rusty, but my average is about 76.",
"Grandpa: Oh really? Chaahooooo I am down to 69.",
"Dad: Congratulations Dad.",
"Grandpa: How about you and I hit a few around next week?",
"Dad: I will have to check my calendar, but I would love to."],

"Creeper Worker":
["Brother: ...and so this guy kept trying to see what I wrote down on my notepad, and I keep trying to hide it from his prying eyes. Anyways...",
"Dad: Hey that reminds me of this guy at work.",
"Brother: I'm trying to tell a story here Dad.",
"Mom: Let Greg finish.",
"Dad: Ok, finish your story.",
"Brother: Well... I forgot where I was going with it. Err, the guy was trying to view my notepad...and well, that's about it. Look what you did Dad.",
"Dad: Sorry. But hey! Now you can hear my story.",
"Dad: Just like you, we had a nosey co-worker. This co-worker was showing around a new customer to our branch when a screensaver caught his in a nearby room.",
"Grandma: What is a screensaver?",
"Dad: You know on a computer when you don't use it and the screen goes black? It is like that, except this computer has an animated display like a slide show.",
"Grandma: Ok, a slide show on the computer.",
"Dad: Yes, sort of like that.",
"Dad: Well, the co-worker enters the room, with the new customer, to check out the screen saver. Now this room belongs to Julia, our PR rep.",
"Dad: I'm not sure why he entered the room. He could have just viewed the screen saver through the office window.",
"Dad: Julia wasn't there at the time, but word gets around quickly in the office.",
"Dad: She found out that Rob, that's the co-worker, entered the room, and filed a complaint with Internal Relations.",
"Dad: Then Internal relations sends a message to Rob, asking if he did enter the room.",
"Dad: And then Rob sends a long email response back, all the while with our customer in tow, even asking the customer advice about what to include in the E-mail.",
"Brother: Wow, so did you lose the customer?",
"Dad: We don't know yet, but management did send an internal memo around re-affirming the boundaries of privacy.",
"Dad: This whole thing was completely overblown though. Rob was just looking at a screensaver. He didn't even try and hide it either.",
"Dad: But that's life. People who get excited over nothing.",
"Wife: Well, he did seem kind of creepy asking for the customer's advice on the E-mail.",
"Brother: And what about Julia? She seemed to know a littttle bit too much about the goings on in her office cubicle.",
"Dad: Maybe she has an office camera or something. I'm not sure.",
"Brother: Do you have one?",
"Dad: No, but then again I'm not in PR. Sometimes workers try and find out what the dirt is on them, or try and change their records on the computer.",
"Brother: Sorry to say, it honestly sounds like a terrible place to work.",
"Dad: It isn't as bad as it seems. Every now and then sometime like this happens and it becomes the talk of the town.",
"Brother: Maybe just a boring place."],

"Paint Bucket Sucks":
["Brother: Hey Grandpa, I've got a funny story about that primer you gave me.",
"Grandpa: You'll have to remind me again, my memory isn't too good in my old age.",
"Brother: Well, you gave me some primer to redo my room.",
"Mom: How is the painting going? Last I heard you had the priming done.",
"Brother: Yup. Well, almost. I still have a mess to clean up.",
"Mom: What happened?",
"Brother: Yeaahh well, grandpa's can of primer was pretty old. And it rusted on the bottom and developed small holes.",
"Brother: So, there I was prepping everything, ready to go to town on the walls, when I start feeling some wetness on my pants.",
"Brother: I look down and there are primer drops all over my pants.",
"Dad: Why were you holding the paint bucket though? Don't you just pour it in a roller pan and do it that way like I taught you?",
"Brother: Well yes, but I was also cutting the edges of the room before hand, like you taught me. And that was easier with the paint bucket in my hand.",
"Brother: Or so I thought...",
"Mom: What happened next Greggy?",
"Brother: Mom, don't call me 'Greggy'.",
"Brother: Anywaaays, I quickly put the can down in the roller pan I had nearby. I turned around to find some paper towels to clean myself off with.",
"Brother: That's when I noticed a drip line all the way from the garage. That's not good.",
"Brother: I dashed for the towels and once I reached them, I tried to soak up as much as possible. And well... not good.",
"Brother: In the future, I probably won't go for your primer Grandpa.",
"Grandpa: You know what'll get that paint out? Some turpentine. If you don't have some of that handy you should try out some kerosene.",
"Brother: I tried some paint remover already, but it also took out the color in my pants. Luckily, I wasn't wearing my best pants.",
"Brother: I did have to go for a heavy duty carpet cleaning service. My wife wasn't too happy about that",
"Grandpa: You should have asked me for help. I would have shown you how to do it, and I would have done it for free too.",
"Brother: Thanks Grandpa, I'll definitely keep that in mind."],

"Hanging Doorway Ornaments":[
"Grandma: A real bother these days are the people that decorations in their doorways. They get in your face as you try to walk through.",
"Grandma: And what if there is an Earthquake!",
"Grandpa: It isn't like we live on a fault line.",
"Grandma: Just stop hanging your bears in the doorway.",
"Grandpa: I have the kitchen and you have the garage, that was the deal.",
"Grandma: Maybe I'll just take both the garage and the kitchen and then put you out on the street with your keychain bears.",
"Grandpa: I'd like to see you try.",
"Grandma: Oohh don't make me get my shotgun.",
"Grandpa: Err, speaking of kitchens. HOW IS THAT TURKEY COMING ALONG IN THERE. YOU NEED A HAND?"],

"Spouse gets surprise movie tickets":
["Mom: Hey, seen any interesting movies y'all?",
"Spouse: I have. Recently I was...",
"Grandpa: Back in my day, we burned rats for fun.",
"Spouse: errr.. Grandpa?",
"Grandma: Don't mind him. He's losing his mind.",
"Grandpa: I keep it right here. *Taps head* But where did you put the lock on that mouse of yours?",
"Dad: Dad, Mom, don't keep interrupting the story.",
"Grandpa: Well, she started it.",
"Grandma: Ahh, you old coot.",
"Mom: Please continue.",
"Spouse: ummmmm",
"Spouse: Ah, now I remember. [Player] and I were at the mall when a woman came up to us.",
"Spouse: 'Hey guys, sorry to bother you. I'm the host of a free movie screening preview, and we are trying to fill as many seats as possible.'",
"Spouse: 'We severely underestimated the number of people who were going to show up. If you have time, it would really help me out if you two would attend.'",
"Spouse: [Player] thought going to see the free movie was a no brainer, but I knew that we had somewhere to be in less than two hours.",
"Spouse: 'How long is the movie', I asked. She replied, 'About an hour and a half'. Which is about standard.",
"Grandpa: Back in my day...",
"Spouse: 'WE CAN ALWAYS leave early', [Player] whispered to me.",
"Dad: Did you end up seeing it?",
"Spouse: Actually, yes.",
"Spouse: We lined up at the theater, and noticed that all the others in line had a pamphlet ticket. We might be in the wrong line!",
"Spouse: The women told us to mention her name 'Stephanine' at the door to get in, but what if we go up to the doorman, mention 'Stephanine',  and they respond ' Stephanine, who is Stephaine?' ",
"Spouse: The line begins to move, and we approach to the ticket-taker.",
"Spouse: 'Stephanie told us to come'. After a heart wrenching pause, the doorman nodded, and we were allowed in.",
"Dad: What movie was it?",
"Spouse: Stephanie mentioned it was going to be an action documentary about Poland but when we got our seats, the pre-ads were all childish.",
"Spouse: Legos, Toys, cartoons, etc. [Player] and I wondered if the movie we were about to see wasn't even what they told us.",
"Brother: Legos aren't just for kids.",
"Spouse: Maybe not, but the marketing is primarily kid focused. Anyhow, the movie turned out to be the Poland one.",
"Spouse: However, the movie was two hours rather than the expected one hour thirty.",
"Mom: Did you stay the whole time? I could not see myself walking out. I would feel too embarrassed about the whole audience staring at me.",
"Spouse: It isn't that hard, you just treat it like you are headed to the bathroom. Except you never come back.",
"Spouse: But yes, we did leave early, so we'll have to check the rest of the movie on DVD, or see it in theatres when it officially releases.",
"Mom: Good thing the staff didn't send a search party for you. Maybe you fell into the toilet",
"Spouse: Haha",
"Dad: Say, what was the title of the movie?",
"Spouse: 'Randy Staples Shares the Pain.' We saw all the build up, but missed the payoff.",
"Grandpa: Back in my day, we used to watch movies for a nickel.",
"Mom: I remember when gas used to be twenty cents a gallon.",
"Brother: And I remember when the PS3 cost $599 US dollars.",
"Cat: Meow, meow meow"],

"Youtube Sensation":
["Grandpa: Back in my day, we burned rats for fun.",
"Brother: Ok Grandpa. Anyways, I was at Frankfort mall the other day.",
"Brother: Just walking around, not really focused on any particular purchase when I noticed a long line. Naturally, you see the line, and wonder what's for.",
"Brother: So, my buddies and I walked up the line to find out the sitch.",
"Mom: What's a 'sitch'.",
"Brother: It means situation.",
"Mom: I see. How long was the line?",
"Brother: Oh, it stretched, maybe, half the mall. There were security guards out, to make sure that traffic could get through gaps in the line.",
"Brother: As we neared the front, we saw that the line moved into some kind of makeup store.",
"Brother: The flier outside said they had one of those video sensations, you know the one who does the makeup? I can't remember her name.",
"Mom: So did you go in?",
"Brother: And wait in that long line? I don't even wear makeup!",
"Mom: Yeah, but what about your fiancee'? Why not get her something nice?",
"Brother: I'm sure she would love some makeup, but I can buy that stuff on any day.",
"Brother: One kind of interesting, but obvious, thing about the line composition was that it was majorly women. There was a handful of guys, but I'd assume they were boyfriends.",
"Grandpa: Back in my day, I would have gotten in that line and wooed all the women.",
"Grandma: You can't even grab the attention of a taxi.",
"Grandpa: You're not making sense. Why would I want to take a taxi out to dinner?",
"Grandma: No, not taking a taxi out to dinner. Forget it. Just forget it."],

"Girlfriend's Boba Keeps on a-flowing":
["Girlfriend: You know what boba is right Mom?",
"Mom: What's Boba?",
"Girlfriend: Ok, I guess not.",
"Grandma: What's booba?",
"Girlfriend: I take it you mean boba?",
"Grandma: Yes, that thing.",
"Girlfriend: What most people talk about when they mean 'boba' are tea drinks with milk in them.",
"Girlfriend: The boba tea drinks are not hard to make, just make black tea, and then add any kind of milk you have, some sweetener, then chill with ice.",
"Girlfriend: [Player] and I made it at home one time, but that's another story. Anyways, the 'boba' itself are these little black balls that are made out of sweet potato.",
"Dad: Sweet Potatoes, like a yam?",
"Brother: Dad, you know that sweet potatoes and yams are not the same right?",
"Dad: What? They aren't?",
"Brother: No",
"Dad: Well, what's the difference?",
"Brother: I don't know, but the point is they are different.",
"Girlfriend: Boba is usually made from sweet potatoes, but it can also be made from other starchy materials, I suppose.",
"Dad: What's it taste like? Kind of...potatoey?",
"Girlfriend: Not really, it is chewy, a bit like... when you take the first bite into some gum. Right before it gets soft.",
"Girlfriend: Though when places heat it up, it is really soft and moldable.",
"Grandma: Hmm. I wouldn't mind trying this boba sometime.",
"Girlfriend: You definitely should since I know you like your morning tea.",
"Girlfriend: Now that you all know what boba is, I can tell you about this cool, and somewhat awkward event that happened.",
"Girlfriend: [Player] and I were driving down the freeway when we remembered that a new boba place was opening up on Teller St.",
"Girlfriend: As part of their opening promotion, they were offering one free boba drink per customer.",
"Girlfriend: Since I was thirsty, I suggested we drop by and see what's up.",
"Girlfriend: We parked and walk up to the building. There weren't too many people about, and a sign revealed why.",
"Girlfriend: The free boba promotion ended at 8PM, and it was already 10!",
"Mom: Aww, that's too bad",
"Girlfriend: I decided to get a drink anyways.",
"Girlfriend: But when I ordered, the worker said 'Would you like to try one of our free drinks?', and motioned towards the sign",
"Girlfriend: 'Sure!', Then he asked [Player] what [GenderPronoun] wanted.",
"Girlfriend: So we both got a full-sized free drink!",
"Mom: What flavor did you get? I assume there are flavors of boba?",
"Girlfriend: Yes, there are. I ordered Strawberry. It tasted ok, but was really missing that strawberry flavor.",
"Girlfriend: The worker asked how they were, and well Mom, you raised me to be an honest individual, so it was lacking in flavor.",
"Girlfriend: So the worker says, 'Alright, let me make you another one'",
"Girlfriend: He makes me a completely new boba drink, while letting me keep the old one to drink. At this point I haven't even paid for anything yet",
"Dad: That's just good customer service. Since this place is new, he is trying to build up customer relations.",
"Girlfriend: True, but I feel like it got a little out of hand. The next drink also lacked the strawberry flavor. The worker said it is probably because of the syrup.",
"Girlfriend: He then proceeded to make another drink, still free, using fresh strawberries in lieu of the syrup flavoring.",
"Girlfriend: Now the syrup drinks were probably really cheap to make, but making drinks with real fruit costs considerably more.",
"Girlfriend: By the end of our time at the place, the two of us had six drinks in hand without a cent spent.",
"Girlfriend: The worker just kept offering us samples and I felt really guilty about being so honest.",
"Girlfriend: I decided to order the drink I was originally going to get, even though I had consumed 2 whole boba drinks already. Sugar overload!",
"Brother: I hope you left him a fat tip for his troubles.",
"Girlfriend: Yes, I tipped, [Player] made sure of that.",
"Girlfriend: With all the caffeine and sugar, I couldn't sleep all night. My heart was in trepidation even through the next morning.",
"Girlfriend: I probably wouldn't do that again.",
"Grandma: This sounds like the place I should try my first boba.",
"Girlfriend: I don't think I could boba for at least a month I'm so burnt out.",
"Brother: It is settled, right after this meal we're all going out for boba.",
"Girlfriend: Hah, no.",
"Brother: No, seriously.",
"Girlfriend: And seriously. No"],


"Grandmother reveals the virtues of the bread line":
["Brother: The Turkey is taking a while to cook. [Player] isn't too good at cooking is [GenderPronoun]?",
"Girlfriend: How dare you talk about [Player] like that. [Player] is a great cook. You'll see!",
"Grandma: You guys have it lucky. Where I grew up we had bread lines.",
"Grandma: My family would stand in a bread line for over six hours with the POSSIBILITY of receiving a loaf of bread.",
"Grandma: I remember one particular occasion where my mom told me to take my baby sister with me and go stand in the bread line.",
"Grandma: I was only 8 years old, and my baby sister was less than a year.",
"Grandma: Standing is a whole day affair. Some people brought laundry. Others did their crafts in line.",
"Grandma: My sister and I stood in that line together for over eight hours until we finally reached the front.",
"Grandma: When we got there. The man with the bread said, 'One loaf of Bread.'",
"Grandma: I held my baby sister outstretched and said 'Two.'",
"Grandma: The bread man responded. 'Baby doesn't count. One loaf of bread.' We were then pushed out of line with our one loaf.",
"Mom: Jesus, that sounds horrible.",
"Grandma: It was, but it was also necessary. Though when I hear people complaining how they are tired of waiting, I like to retell that story.",
"Brother: Alright, I suppose it could be worse, but let's hope that [Player] can do better than that."],

"Father talks about the virtues of Automated Cars":
["Mom: Roger, tell everyone about your automated cars meeting.",
"Dad: It wasn't a meeting, it was closer to a seminar.",
"Dad: At work, we accrue credits that can be put towards educational events. Our managers think that an educated workforce is a happy and productive workforce.",
"Dad: So we are required to spend these credits every year on our choice of relevant education events.",
"Girlfriend: That's cool. What kind of choices for educational events are there?",
"Dad: As one example, employees can go to a local college or high school and present about their work at the company.",
"Dad: Other options are to attend talks about various topics, such as aerospace engineering, materials science, manager relations, customer relations, etc.",
"Dad: I decided to spend my credits on a five person panel from the various automotive manufacturers about the future of automated vehicles.",
"Dad: Disappointingly, the panel never went in-depth about the technology side of automated cars.",
"Dad: The panel just already affirmed what I already knew. Self-driving cars are coming.",
"Grandpa: Why would you want a self-driving car anyways? Driving is fun!",
"Grandpa: I remember driving my old station wagon across country to California. Now that was a trip to remember.",
"Grandpa: The sun was beating down, and we didn't have air conditioning in the car, so you rolled down the window and enjoyed the breeze.",
"Grandpa: Nowadays, you are spoiled with automatic windows, automatic car washers, automatic transmission.",
"Grandpa: Why even call it a car? Sounds to me more like a train you ride.",
"Dad: Yes Dad, which was the general gist of the whole thing. Some people like to drive their car.",
"Dad: Though one panelist seemed confident that it will eventually take over.",
"Dad: They quoted 48 minutes as the average amount of time a driver spends in their car per day.",
"Dad: If most of that time is spent in traffic, or just getting somewhere, then people will adopt a car that can do the nitty gritty driving.",
"Dad: Drivers can then spend their five leisure minutes on the beach boulevard cruising with manual control.",
"Grandpa: Enjoy your fandangled self-driving cars, if they ever come.",
"Grandpa: In the 1960s they used to say we'd have flying cars in the 2000s, but you don't see that now.",
"Brother: Maybe in my generation. First the self-driving cars, then the flying ones.",
"Cat: Meow (and then the world!)"],

"Brother recounts a hockey game he saw recently, and his friend has to go to the hospital":
["Brother: Yo, I watched a hockey game recently. There were cheap group tickets, so a bunch of my friends jumped on it to watch the game.",
"Girlfriend: Who was playing?",
"Brother: Some minor league team, the 'Raging Tornados', I believe?  It isn't important. The point is seeing two teams pummel each other over a little puck.",
"Grandpa: Yes, exactly!",
"Girlfriend: I suppose since we're glorifying the violence of the sport, were there any fights?",
"Brother: Ah hell yeah! The gloves were thrown to the ice, and the two players starting man-hugging each other.",
"Brother: The refs just let it go. There was no blood, but it was the intention that mattered.",
"Brother: Sadly, it isn't like some video games where the winner of the fight gets to stay on the ice. The perpetrator in this case got the penalty.",
"Brother: But anyways, what was cool was we were allowed to play some broomball on the ice before the game due to our group size.",
"Brother: That was loads of fun. Until someone got injured.",
"Mom: Heavens no!",
"Brother: Well, it wasn't from the broomball.",
"Brother: Later, when our group was walking around, waiting for the actual game to start, the two hockey teams were practicing and a puck flew into the crowd.",
"Brother: It smacked one of my friends in the neck, and they had to go to the infirmary.",
"Mom: But were they okay?",
"Brother: Yeah, they were fine. They decided to go home however. Too much trauma. They would be flinching with every one-timer during the game.",
"Mom: Aww, that's a shame. It wasn't Charles was it? Poor Charles...",
"Brother: No, Mom, Charles is fine.",
"Girlfriend: Close game?",
"Brother: Hardly. 3-0",
"Brother: The tornado mascot kept it interesting though, with his kazoo.",
"Brother: 'Bzzzwoooooo'",
"Brother: Ah, here's something. A Catholic girl's school came to sing the national anthem.",
"Brother: You have to imagine these girls were about five to six years old. So it was mind-numbingly cute.",
"Brother: The stadium was filled with 'awwws' when they approached the mics.",
"Brother: Well anyways, these girls were out near the mechanical bull before the game started.",
"Dad: The stadium has a mechanical bull?",
"Brother: Yup, pay your five dollars and take it for a ride. The operators know their clientele.",
"Brother: They let young kids 'tame the bull' while they throw the wrath of God down on the teenagers. Cause they know the teens want to flex their muscle.",
"Brother: I watched one teen tumble backwards over his head and shoulders in one bout.",
"Brother: The best part though was those little girls I mentioned earlier.",
"Brother: They surrounded the bull-riding-rink, all dressed in their school outfits.",
"Brother: 'Ride the bull. Ride the Bull!', They shouted in unison.",
"Brother: Then when someone got on.",
"Brother: 'Make them fall, make them fall!'",
"Mom: Dawwww",
"Brother: No Mom! Those little girls are evil!",
"Brother: But, it was definitely a lot of fun to watch."],

"Mom talks about her students and reading over summer vacation":
["Girlfriend: Well Mom, how are your students doing?",
"Mom: Thank you for asking. They are doing well.",
"Brother: Still teaching the third grade?",
"Mom: Yessum",
"Girlfriend: Soo, lay on the juicy stories.",
"Mom: Mmmm, well, for the winter break coming up I'm planning on having them read 'The BFG'.",
"Girlfriend: oooh, I liked that book.",
"Brother: Mom, winter break reading is THE reason that students hate their teachers. Can't you let them enjoy their break in peace?",
"Mom: But reading is fundamental. We can't let our students forget what they learned.",
"Girlfriend: It isn't that bad, 'The BFG' is a fun and entertaining book.",
"Brother: Granted, but forcing one to read kills their love of reading. It did for me.",
"Brother: After I began reading for fun rather than the school forcing me to do it, I could really appreciate the work for what they are.",
"Mom: Greg, you are right. But you have to remember that if we don't force kids to do a little reading, they may not do the reading at all.",
"Mom: I sleep better knowing that my students have been given the opportunity discover works they like, whether or not a little encouragement was given.",
"Brother: You are an inspiration to us all.",
"Mom: That's very kind of you to say."],

"Grandmother reveals her name":
["Grandpa: Lana, did I ever tell you that I am blessed to be married to you?",
"Grandma: Well, you just know all the right things to say to make a woman feel good.",
"Brother: Grandma, if you don't mind me asking, I was wondering if your name, 'Lana' had any special meaning in Russian.",
"Brother: Like, I know some American names, like Mark, are biblical in nature.",
"Grandma: Ahh, well yes. Very similar",
"Grandma: Lana is short for Svetlana, which was my given name. I shortened it to 'Lana' because it was easier to pronounce in those parts.",
"Brother: Sweatlana?",
"Grandma: Close, but you need to put more 'V' into it.",
"Grandma: Stalin's daughter was named Svetlana, and so many mothers named their daughters the same in honor.",
"Grandma: It was be loosely translated to light, and holy. Sort of biblical as you mentioned.",
"Brother: That's very interesting. Mom, Dad, was there any special reason for naming me Greg?",
"Mom: Well.",
"Dad: We looked at a lot baby naming books, and we were having trouble deciding.",
"Mom: I had a good friend named Greg when I was growing up so I liked that name.",
"Dad: It sounded good to me, and you ended up a boy, so it worked out.",
"Brother: So, did the 'Greg' you knew Mom, do anything special or notable? Like, was he famous?",
"Mom: Uhhh, well, we dated for a while, but it didn't work out.",
"Brother: Whaat? I'm named after your former lover?! Did you know about this Dad?!",
"Dad: Yes, but what's the big deal? I still like the name Greg. It's a good strong name.",
"Brother: I don't think I'll be able to think about my name the same way ever again.",
"Girlfriend: Hah ha brother. Sucks to be you. Hah ha!",
"Girlfriend: But please Mom and Dad, don't tell ever me how I got my name.",
"Mom: Ooh, but your name origin is quite special.",
"Girlfriend: La la la, I'm not listening!"],

"Grandparents sings a Patriotist song":
["Grandpa: Since dinner is taking a while, it seems like a good time for a song don't you think?",
"Dad: Dad, please no...",
"Grandpa: Ooooh, I saw Mussolini sitting on a log",
"Grandpa: All puffed up like a great big frog",
"Grandpa: Sneaked up close and stuck him with a wire",
"Grandpa: And he just went poof like an old flat tire.",
"Grandpa: took his hide and hung it on a tree,",
"Grandpa: and he said 'hey don't do that to me' ",
"Grandpa: so I took it on home to my mother in law",
"Grandpa: She threw me outside with the Turkey in the Straw",
"Grandma: Oooooh Adolf Hitler grabbed a tail, ",
"Grandma: And he hung right on with tooth and nail, ",
"Grandma: and he saw what he had and he began to swear, ",
"Grandma: On the end of the tail was a Russian bear, ",
"Grandpa: The old bear growled and started in to shake, ",
"Grandma: Adolf knew he'd made a big mistake.",
"Grandpa: He tried to hang on and he tried to let go ",
"Grandma: Now they have a new dance called Hitler in the snow. ",
"Grandpa: Wow, I didn't know you knew that one. ",
"Grandma: Word travels fast on the front. Just don't let the officers hear you singing it or they'll whoop your ass faster than you can say vodka. ",
"Grandpa: Advice to keep close at heart. "],

"Dad Tells a Bad Dad Joke":
["Dad: Hey guys, what's the key to a great Thanksgiving dinner?",
"Mom: Of course it is the loving family?",
"Brother: I bet it is the pillowy mounds of mashed potatoes.",
"Girlfriend: It is the turkey right?",
"Dad: That's right, its the turKEY",
"Dad: turKEY, get it?",
"Girlfriend: What?",
"Dad: The KEY to a great thanksgiving dinner is the turKEY.",
"Girlfriend: Aww, come on Dad. That's terrible.",
"Grandma: Is this a joke?",
"Dad: Yes Mom,",
"Grandma: Well, what do you mean 'key' .",
"Dad: A 'key', something that is of vital importance.",
"Grandma: hmmm, ok. I think I get it.",
"Dad: Ok...."],

"Mom Butter Story":
["Mom: My favorite color is butter.",
"Girlfriend: That's cool."],

"Cat Story":
["Cat: Meow Meow Meow Meow Meow",
"Dad: I think the cat's hungry!",
"Cat: Meow",
"Mom: Look at it, poor thing wants some turkey!",
"Cat: Meow",
"Cat: (Translation) If you turn the oven past 1000 degrees, something fun happens!"],

"Cat Story II":
["Cat: Meow Meow Meow!",
"Mom: What is it, sweetie?",
"Cat: Meow Meow Meow!",
"Cat: (Translation) Why aren't we cooking fish? I want fish for dinner.",
"Mom: Yes sweetie, that's an oven with a turkey inside! We're going to have a nice dinner.",
"Cat: Meow",
"Cat: (Translation) It's like you don't love me anymore.",
"Mom: It'll be done very soon, I promise! You can have a few bites.",
"Cat: Meow Meow Meow Meow!",
"Cat: (Translation) I don't want turkey, I want fish!"],


"Mom Talks About Her Bathroom Policy and her Students":
["Mom: I make sure my students are well hydrated and well rested.",
"Mom: We have 20 minutes of reading time, 20 minutes of sleeping time, and 20 cumulative daily minutes of bathroom time.",
"Mom: I bring bottles of water and juice on my own dime to make sure the students are at maximum productivity.",
"Dad: What if someone needs to use the restroom for 30 minutes?",
"Mom: It doesn't bug me, but the school has some strict bathroom policies. I've gotten in trouble in the past.",
"Dad: Oh, You never told me about this. What happened honey?",
"Mom: I didn't want to bother you with the details. But I guess there's no harm in letting you know.",
"Mom: For a while I allowed all my students to use the bathroom whenever they wanted. They didn't even have to ask. I wanted the students to feel independent.",
"Mom: But then the administration told me that all students were required to have a bathroom pass. Too many students were skipping class they feared.",
"Mom: I never lost a student and all my students knew not to abuse their privileges, but I did as I was told.",
"Mom: I made sure students signed themselves out, wrote their name, signed it, then took the bathroom pass.",
"Girlfriend: That seems very efficient. But are the third graders mature enough to get themselves to the bathroom and not goof off?",
"Mom: Well, every student has their 20 minutes. I don't want to parent them. That's not my job. My job is to teach lessons.",
"Mom: It seemed to work well. None of my students abused the system.",
"Mom: But it seemed the administration didn't appreciate the system. They changed the rules once again.",
"Mom: Now students are only allowed to go to the bathroom once per day. No more than 5 minutes or else I have to go looking for them.",
"Mom: I told all my students. 'Make sure you use the restroom at recess and before school'. And they did.",
"Brother: Your students seem very well behaved. I can't even imagine a class of third graders acting as well-mannered as you describe.",
"Mom: You would be surprised what putting a little trust in a person can do.",
"Mom: Well, the newest method was working dandy. I wouldn't say it was as good as what we had setup before, but it was fine.",
"Mom: Less than a week later however, I got another memo.",
"Mom: 'Students are to be allowed to use the restroom facilities whenever they need.",
"Dad: They reverted their one-bathroom per child policy?",
"Mom: I hate to bring this up at the dinner table.",
"Grandma: Don't be worrying. Tell us the story.",
"Mom: Sigh, ok. One of the students in the other class, not mine of course, had to use the restroom. But she had already used her one bathroom break.",
"Mom: So the teacher told her to go back to her seat.",
"Mom: A while later....",
"Brother: Ahh geeez, she peed everywhere?",
"Mom: Greg!",
"Brother: What? It isn't like this is the first time this has ever happened? I hear about this happening all the time on internet message boards.",
"Mom: It was certainly a surprise for me!",
"Dad: I'm sorry to, hehehe, hear that honey.",
"Mom: This isn't a laughing matter.",
"Dad: Sorry ma'am."],

"Grandpa tells a story about how a bug crawls in the ear of one of his fellow army buddies during the Korean War":
["Grandpa: Mmmm mmm, I can't wait to hear the sizzling of that turkey.",
"Grandma: You never seem to hear when I call you.",
"Grandpa: That's called selective hearing. My hearing is fine.",
"Grandpa: Which reminds me of my old friend Jimmy.",
"Grandma: How is ol' Jimmy?",
"Grandpa: Deaf in the one ear as usual, but he couldn't be a happier soul. We're going golfing next week.",
"Mom: I don't believe I've met Jimmy.",
"Grandpa: He and I go way back. We were GIs together during the Korean War. Then he lost his hearing.",
"Brother: Was it due to the loudness of the guns? A mortar round? Shrapnel?",
"Grandpa: I don't know what the media has filled your noggin with, but not all injury in war is glamorous.",
"Brother: I agree, war is terrible. But, I must say the technology is interesting.",
"Grandpa: Be glad you don't have to serve and only reap the riches of wartime development.",
"Grandpa: As for Jimmy, he lost his hearing at camp.",
"Grandpa: We went to sleep for the night and a beetle bug crawled in his ear.",
"Grandpa: Tried to fish it out but he ended up crushing it.",
"Grandpa: Field medics couldn't get all the pieces out, and we were at least two days away from a decent hospital.",
"Grandpa: The ear got infected and Jimmy lost his hearing soon after.",
"Grandpa: 'Bug Brain' we used to call him. Great guy.",
"Girlfriend: I'm sorry to hear that.",
"Grandpa: Can't undo the past. Those dang bugs were everywhere though.",
"Mom: Gross, Gross, Gross. ",
"Grandpa: It isn't that bad. Be grateful I didn't tell you the story where we ate them. Not bad. A little crunchy. Not as good as turkey though.",
"Mom: !!!"],

"Story about Girlfriend's teacher that makes buzzer noises when you got something wrong":
["Girlfriend: Greg, here's something that might tinkle your fancy.",
"Girlfriend: I saw my old professor from a couple years back, Professor Ronfleur. The Humanities teacher. Do you remember him?",
"Brother: The guy who always wore the purple bow tie? Who could forget him? Did he buzz you?",
"Girlfriend: Ha-ha, no, but that's why I brought it up. That buzz!",
"Mom: What buzz?",
"Girlfriend: I guess we never told you Mom. Remember when we took that humanities class at the local community college during the summer?",
"Girlfriend: We were trying to get the lower division English requirements out the way so could take classes at college that were actually worth our time.",
"Girlfriend: This Professor Ronfleur used to make a buzzing sound whenever anybody got something wrong.",
"Girlfriend: 'In what way does Aristotle disagree with Plato's Allegory of the Cave?' and then...",
"Girlfriend: BRRZZZZZZZT!",
"Girlfriend: He would make this super nasally buzzing noise.",
"Brother: Seriously! Whenever I see the guy, I can just imagine pressing his bow tie and a buzzing noise coming out.",
"Girlfriend: And he did it ALL. THE. TIME.",
"Brother: Yeah! Did he say anything to you when he saw you?",
"Girlfriend: I said hello and introduced myself, but he didn't know me. Just gave me the glazed ham eye look.",
"Brother: Glazed ham?",
"Girlfriend: For Thanksgiving.",
"Brother: He gave you the glazed turkey look.",
"Girlfriend: Exactly."],

"Brother's Fiancee is on Business Trip":
["Mom: Greg, where's your fiancée? Why didn't you invite her over for Thanksgiving dinner?",
"Brother: I did invite her, but she couldn't make it. She is on a business trip and could not get the time off.",
"Mom: A business trip on Thanksgiving? But Thanksgiving only happens once per year! This is the perfect time to rekindle the spirit of family.",
"Brother: I know Mom, but Thanksgiving doesn't happen everywhere, and her job in sales demands that she travel abroad to meet with potential clients in person.",
"Brother: I miss her a lot when she leaves, but whenever she returns home, we make every moment count. We count our blessings every day.",
"Mom: Amen",
"Brother: Though, it is too bad that since we're both so busy all the time, our new house remains largely unoccupied throughout the day.",
"Mom: Awww honey, I'll have to come and visit.",
"Brother: uh, well yeah, sure Mom. You can come and visit.",
"Grandpa: What!? I want to come and see your new place too.",
"Brother: Sure...yeah ok.",
"Girlfriend: You aren't going to invite me?",
"Brother: Yes, definitely. Everyone can come and visit. Just... I don't want to stress out my fiancée when she comes home.",
"Brother: She likes to relax at home.",
"Mom: Don't worry honey, we won't stress her out. I'll make her my delicious breakfast omelet.",
"Grandpa: And I'll tell her my war stories.",
"Brother: Oh, good..."],

"Turkey Fact - Snood": 
["Turkey: Gobble Gobble. Turkeys have a fleshy bit that comes off their forehead called the snood. Turkey farmers will occasional remove the snood, in a process called 'de-snooding'.",
"Turkey: Male turkeys like their snood intact to attract a mate, and for dominance. Be kind to your turkey. Do not lose the snood."],

"Turkey Fact - Cat Puns": 
["Turkey: Gobble Gobble. I suppose it is too late to ask you not to eat me. But is it too late to ask for you to kick that cat of yours?",
"Cat: Hey Turkey, it has been a long time. I see you're dead.",
"Turkey: Kasey, how dare you speak to me. First, you steal my plans for world domination and now you gloat at my passing. For shame.",
"Cat: It isn't my fault you taste so delicious. I'm going to delight in eating your flesh. Maybe if I beg enough they may give me your head on a platter",
"Turkey: Oooh, don't get me fired up.",
"Cat: Meow meow meow! The oven is doing that quite nicely.",
"Turkey: Ga-Gobble!",
"Cat: Meow Meow",
"Dad: Aww Kasey, aren't you a cute little kitty."],

"Turkey Fact - Wattle":
["Turkey: Hey, it is time for another turkey fact.",
"Turkey: Most people will recognize the wattle on a chicken as that piece of red flesh that hangs down from the beak.",
"Turkey: But did you know turkeys have them too?",
"Turkey: I personally believe they are much sexier on a turkey than a chicken anyhow. And you can bet a fine wattle will attract the hen's attention.",
"Turkey: Gobble Gobble"],

"Turkey Fact - Unsuscribe":
["Turkey: I hope I'm worth it. But hey, now you can listen to a wonderful fact about turkeys.",
"Turkey: Turkeys are members of the order Galliformes. That means we share relations to other birds like the chicken and pheasant.",
"Turkey: To unsubscribe from Turkey facts, please gobble like a turkey into the microphone.",
"Turkey: 'Gobble' in 3",
"Turkey: 2",
"Turkey: 1",
"Turkey: Now Recording...",
"Turkey: I'm sorry, we didn't recognize your dialect. Please try again soon.",
"Turkey: You are now automatically renewed for another full year of Turkey Facts",
"Turkey: Please have a nice day."],

"Turkey Fact - genus":
["Turkey: My friend, welcome to another fantastic turkey fact!",
"Turkey: Today we're learning that turkeys are in the genus Meleagris.",
"Turkey: This is probably useless information for you. Good!",
"Turkey: Until next time."],

"Turkey Fact - gobble":
["Turkey: The turkey is often associated with the gobble sound. But that is just sexist.",
"Turkey: Only male turkeys gobble. Females instead make cooing and clicking noises. Put an end to stereotypes!"],

"Turkey Fact - poult":
["Turkey: Don't eat me, I have children. Zillions of children.",
"Turkey: But since we're talking about children, did you know that a young turkey is called a poult?",
"Turkey: Now you do.",
"Turkey: By the way, the best way to cook a turkey is to not at all."],

"Turkey Fact - World Dominination":
["Turkey: Hey Kasey.",
"Cat: What may I do for you juicy?",
"Turkey: Don't piss off turkeys or they'll gang up on you.",
"Turkey: That's because a group of turkeys is called a gang.",
"Turkey: A turkey group may also be called a rafter.",
"Turkey: I'm more of a kayaker personally.",
"Cat: Get meowta here",
"Turkey: That pun was fowl",
"Cat: Purrrsonally, not as bad as yours.",
"Turkey: Gobble Gobble"]

};
