define(function (require) {

    var FacilityList = require('facilityList');

    describe('facility list', function() {

        describe('addFacility', function() {
            it('adds a facility', function() {
                // Arrange
                var f1 = {};
                var facilityList = new FacilityList();

                // Act
                facilityList.addFacility(f1);
                var result = facilityList.facilities;

                // Assert
                expect(result).toEqual([f1]);
            });
        });

        describe('removeFacility', function() {
           it('removes a facility', function() {
               // Arrange
               var f1 = {};
               var f2 = {};
               var facilityList = new FacilityList();
               facilityList.addFacility(f1);
               facilityList.addFacility(f2);

               // Act
               facilityList.removeFacility(f1);
               var result = facilityList.facilities;

               // Assert
               expect(result).toEqual([f2]);
           }) ;
        });

        describe('annualPollutionDifference', function() {
            it('returns sum of pollution generated by each facility', function() {
                // Arrange
                var f1 = { annualPollutionDifference: 100 };
                var f2 = { annualPollutionDifference: -75 };
                var f3 = { annualPollutionDifference: 30 };
                var facilityList = new FacilityList();
                facilityList.addFacility(f1);
                facilityList.addFacility(f2);
                facilityList.addFacility(f3);

                // Act
                var pollutionDifference = facilityList.annualPollutionDifference();

                // Assert
                expect(pollutionDifference).toBe(55);
            });
        });

    });
});
